### ISSUE TITLE
firmware binary is invalid, magic byte=FF

### ISSUE THREAD

**Issue by Rumczeis** [ah01/Tasmota-Vindriktning#2]
Při nahrávání [tasmota-vindriktning-2022-02-08.factory.bin] pomocí ESP-Flasher.exe dojde k chybě rozpoznání firmware:

```
Using 'COM12' as serial port.
Connecting....
Detecting chip type... Unsupported detection protocol, switching and trying again...
Connecting....
Detecting chip type... ESP32
Connecting....

Chip Info:
 - Chip Family: ESP32
 - Chip Model: ESP32-D0WDQ5 (revision 1)
 - Number of Cores: 2
 - Max CPU Frequency: 240MHz
 - Has Bluetooth: YES
 - Has Embedded Flash: NO
 - Has Factory-Calibrated ADC: YES
 - MAC Address: 8C:CE:4E:A8:FC:98
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
 - Flash Size: 4MB
Unexpected error: The firmware binary is invalid (magic byte=FF, should be E9)
```

**Comment by ah01** [comment]
*ESP-Flasher.exe* jsem nikdy nepoužíval, takže nedovedu na první pohled říct v čem může být problém. Vím o několika lidem, který flashnutí pomocí samotného esptool fungovalo. ESP-Flasher.exe je podle podle všeho nad esptool postavený, ale asi nad tím dělá nějakou magii.

Můžete vyzkoušet esptool, jestli je chyba opravdu v samotném souboru, nebo někde na straně ESP-Flasher? (bohužel teď nemám u sebe potřebný HW)

**Comment by Rumczeis** [comment]
Potvrzuju funkčnost flashování skrz esptool.py. Zapátral jsem a ona i samotná Tasmota má koukám u ESP32 bin soubory pro esp-flasher a jiné (s označením factory.bin) pro esptool. 
Díky

**Comment by ah01** [comment]
Super. Díky za potvrzení.

PS: Dvou bin souborů jsem si všiml, ale nikdy jsem nepátral k čemu je ten druhý, takže díky za vysvětlení.
